// lib/models/driving_session.dart
import 'package:autoperf_monitor/models/fuel_record.dart';
import 'package:autoperf_monitor/models/gps_point.dart';
import 'package:autoperf_monitor/models/performance_metrics.dart';

enum DrivingMode {
  stationary,
  urban,
  highway,
  aggressive,
}

class DrivingSession {
  final int? id; // Added for database primary key
  final DateTime startTime;
  final DateTime? endTime;
  final List<GPSPoint> trajectory;
  final PerformanceMetrics metrics;
  final FuelRecord? refueling;

  DrivingSession({
    this.id, // Made optional as it's often auto-generated by the DB
    required this.startTime,
    this.endTime,
    required this.trajectory,
    required this.metrics,
    this.refueling,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'startTime': startTime.millisecondsSinceEpoch,
      'endTime': endTime?.millisecondsSinceEpoch,
      // Metrics and Refueling are stored by ID or in separate tables
    };
  }

  DrivingSession copyWith({
    int? id,
    DateTime? startTime,
    DateTime? endTime,
    List<GPSPoint>? trajectory,
    PerformanceMetrics? metrics,
    FuelRecord? refueling,
  }) {
    return DrivingSession(
      id: id ?? this.id,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      trajectory: trajectory ?? this.trajectory,
      metrics: metrics ?? this.metrics,
      refueling: refueling ?? this.refueling,
    );
  }
}
