// lib/models/fuel_record.dart
enum FuelType {
  petrol,
  diesel,
  electric, // Although not 'fuel', good for futureproofing
  lpg,
  cng,
  other,
}

class FuelRecord {
  final int? id; // Added for database primary key
  final DateTime date;
  final double amount; // in currency
  final double liters;
  final double mileage; // current odometer reading
  final FuelType fuelType;

  FuelRecord({
    this.id, // Made optional as it's often auto-generated by the DB
    required this.date,
    required this.amount,
    required this.liters,
    required this.mileage,
    required this.fuelType,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'date': date.millisecondsSinceEpoch,
      'amount': amount,
      'liters': liters,
      'mileage': mileage,
      'fuelType': fuelType.name,
    };
  }
}
