// Mocks generated by Mockito 5.4.6 from annotations
// in autoperf_monitor/test/mocks/mock_geolocator_platform.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:autoperf_monitor/database/database_helper.dart' as _i8;
import 'package:autoperf_monitor/models/driving_session.dart' as _i4;
import 'package:autoperf_monitor/models/fuel_record.dart' as _i9;
import 'package:autoperf_monitor/models/maintenance_record.dart' as _i10;
import 'package:geolocator_platform_interface/src/enums/enums.dart' as _i7;
import 'package:geolocator_platform_interface/src/geolocator_platform_interface.dart'
    as _i5;
import 'package:geolocator_platform_interface/src/models/models.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDrivingSession_2 extends _i1.SmartFake
    implements _i4.DrivingSession {
  _FakeDrivingSession_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeolocatorPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocatorPlatform extends _i1.Mock
    implements _i5.GeolocatorPlatform {
  MockGeolocatorPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i6.Future<_i7.LocationPermission>.value(
              _i7.LocationPermission.denied,
            ),
          )
          as _i6.Future<_i7.LocationPermission>);

  @override
  _i6.Future<_i7.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i6.Future<_i7.LocationPermission>.value(
              _i7.LocationPermission.denied,
            ),
          )
          as _i6.Future<_i7.LocationPermission>);

  @override
  _i6.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i2.Position?> getLastKnownPosition({
    bool? forceLocationManager = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownPosition, [], {
              #forceLocationManager: forceLocationManager,
            }),
            returnValue: _i6.Future<_i2.Position?>.value(),
          )
          as _i6.Future<_i2.Position?>);

  @override
  _i6.Future<_i2.Position> getCurrentPosition({
    _i2.LocationSettings? locationSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, [], {
              #locationSettings: locationSettings,
            }),
            returnValue: _i6.Future<_i2.Position>.value(
              _FakePosition_0(
                this,
                Invocation.method(#getCurrentPosition, [], {
                  #locationSettings: locationSettings,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.Position>);

  @override
  _i6.Stream<_i7.ServiceStatus> getServiceStatusStream() =>
      (super.noSuchMethod(
            Invocation.method(#getServiceStatusStream, []),
            returnValue: _i6.Stream<_i7.ServiceStatus>.empty(),
          )
          as _i6.Stream<_i7.ServiceStatus>);

  @override
  _i6.Stream<_i2.Position> getPositionStream({
    _i2.LocationSettings? locationSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, [], {
              #locationSettings: locationSettings,
            }),
            returnValue: _i6.Stream<_i2.Position>.empty(),
          )
          as _i6.Stream<_i2.Position>);

  @override
  _i6.Future<_i7.LocationAccuracyStatus> requestTemporaryFullAccuracy({
    required String? purposeKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestTemporaryFullAccuracy, [], {
              #purposeKey: purposeKey,
            }),
            returnValue: _i6.Future<_i7.LocationAccuracyStatus>.value(
              _i7.LocationAccuracyStatus.reduced,
            ),
          )
          as _i6.Future<_i7.LocationAccuracyStatus>);

  @override
  _i6.Future<_i7.LocationAccuracyStatus> getLocationAccuracy() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationAccuracy, []),
            returnValue: _i6.Future<_i7.LocationAccuracyStatus>.value(
              _i7.LocationAccuracyStatus.reduced,
            ),
          )
          as _i6.Future<_i7.LocationAccuracyStatus>);

  @override
  _i6.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  double distanceBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#distanceBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);

  @override
  double bearingBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bearingBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i8.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i3.Database>);

  @override
  _i6.Future<_i4.DrivingSession> insertDrivingSession(
    _i4.DrivingSession? session,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertDrivingSession, [session]),
            returnValue: _i6.Future<_i4.DrivingSession>.value(
              _FakeDrivingSession_2(
                this,
                Invocation.method(#insertDrivingSession, [session]),
              ),
            ),
          )
          as _i6.Future<_i4.DrivingSession>);

  @override
  _i6.Future<List<_i4.DrivingSession>> getDrivingSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getDrivingSessions, []),
            returnValue: _i6.Future<List<_i4.DrivingSession>>.value(
              <_i4.DrivingSession>[],
            ),
          )
          as _i6.Future<List<_i4.DrivingSession>>);

  @override
  _i6.Future<int> insertFuelRecord(_i9.FuelRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#insertFuelRecord, [record]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i9.FuelRecord>> getFuelRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getFuelRecords, []),
            returnValue: _i6.Future<List<_i9.FuelRecord>>.value(
              <_i9.FuelRecord>[],
            ),
          )
          as _i6.Future<List<_i9.FuelRecord>>);

  @override
  _i6.Future<int> updateFuelRecord(_i9.FuelRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#updateFuelRecord, [record]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteFuelRecord(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFuelRecord, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> insertMaintenanceRecord(_i10.MaintenanceRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#insertMaintenanceRecord, [record]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i10.MaintenanceRecord>> getMaintenanceRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenanceRecords, []),
            returnValue: _i6.Future<List<_i10.MaintenanceRecord>>.value(
              <_i10.MaintenanceRecord>[],
            ),
          )
          as _i6.Future<List<_i10.MaintenanceRecord>>);

  @override
  _i6.Future<int> updateMaintenanceRecord(_i10.MaintenanceRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#updateMaintenanceRecord, [record]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteMaintenanceRecord(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMaintenanceRecord, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}
